import { UserType } from './type';

export const DEFAULT_PROFILE_URL =
  'https://api.dicebear.com/9.x/micah/png?seed=';

export const User: UserType = {
  name: 'Anirban Paul',
  designation: 'Software Engineer',
  site: `https://anirbanpaul.vercel.app`,
  about: '',
  contact: {
    email: 'anirbanpaulaps@gmail.com',
    phone: '',
    github: 'https://github.com/anirbanpaulcom',
    linkedin: 'https://www.linkedin.com/in/anirbanpaulcom',
    instagram: 'https://www.instagram.com/anirbanpaulcom',
    twitter: '',
    cal: 'https://cal.com/anirbanpaulcom/letsconnect',
  },
  skills: [
    'C++',
    'Typescript',
    'JavaScript',
    'Python',
    'Go',
    'Swift',
    'Kotlin',
    'React',
    'React Native',
    'Next.js',
    'Tailwind CSS',
    'CSS3',
    'HTML5',
    'SASS/SCSS',
    'Node.js',
    'Express.js',
    'Django',
    'Flask',
    'GraphQL',
    'RESTful APIs',
    'MongoDB',
    'PostgreSQL',
    'MySQL',
    'SQLite',
    'Firebase',
    'Redis',
    'Cassandra',
    'ElasticSearch',
    'Docker',
    'Kubernetes',
    'AWS',
    'Azure',
    'Google Cloud',
    'Terraform',
    'Jenkins',
    'CI/CD',
    'Git',
    'GitHub',
    'GitLab',
    'Bitbucket',
    'Jest',
    'Figma',
    'Adobe',
    'Photoshop',
    'Jira',
    'TensorFlow',
    'PyTorch',
    'Keras',
    'OpenCV',
    'Pandas',
    'Zod',
    'Redux',
    'WebSocket',
    'WebRTC',
    'Socket.io',
    'Nginx',
    'Apache',
    'Visual Studio Code',
    'Postman',
    'GraphQL',
    'Bash Scripting',
    'Linux Command Line',
  ],
  experiences: [],
  blogs: [
    {
      filename: 'sanjeevni',
      title: 'Sanjeevni AI',
      description:
        'Sanjeevni AI uses AI to improve healthcare access in rural India through voice-first, multilingual health assessments, telemedicine, and education, empowering local healthcare workers and addressing key challenges.',
      date: 'October 30, 2023, 12:00 PM',
      category: 'Health',
    },
  ],
  images: [
    'https://github.com/user-attachments/assets/16ff28d4-b3b5-4425-b57b-8ad6465d7b71',
  ],
  recommendations: [
    {
      name: 'Daniel Silva',
      review:
        'I had the pleasure of mentoring Anirban during his Google Summer of Code (GSoC) internship while we were working on the mobile project at Rocket.Chat. Anirban demonstrated exceptional technical skills, a strong work ethic, and a keen ability to tackle complex challenges. Throughout the GSoC program, Anirban was proactive in learning and applying new concepts, and he consistently delivered high-quality work. His dedication and enthusiasm were evident in every task he undertook, and his contributions significantly advanced our project. Anirban’s collaborative spirit and problem-solving capabilities make him a valuable asset to any team. I have no doubt that he will continue to excel and make meaningful contributions in his future endeavors. I highly recommend him for any role or opportunity that aligns with his skills and passions.',
    },
    {
      name: 'Rajdeep Ghosh',
      review: `I highly recommend Anirban Paul, with whom I've collaborated on multiple projects. Anirban's expertise in Fullstack and app development is commendable, as he consistently delivers high-quality solutions by seamlessly integrating front-end and back-end technologies. What sets Anirban apart is his remarkable ability to quickly adapt and learn new technologies, making him a valuable asset in dynamic and evolving work environments. His dedication, technical proficiency, and collaborative approach make him an excellent choice for any Fullstack development project.`,
    },
  ],
};
